
version: "3.9"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus
    ports: ["9090:9090"]
  grafana:
    image: grafana/grafana:10.4.2
    ports: ["3001:3000"]
    volumes:
      - ./ops/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./ops/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - graf_data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/otp.json
volumes:
  prom_data: {}
  graf_data: {}
